spring:
    datasource:
        url: jdbc:mysql://localhost:3306/spring_social?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        username: root
        password: 3050
    servlet:
        multipart:
          max-file-size: 10MB
          max-request-size: 10MB
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    security:
      oauth2:
        client:
          registration:
            google:
              clientId: 137685191866-re0l8qip4ekvkq0l5krnlkmvil7hqerj.apps.googleusercontent.com
              clientSecret: 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
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile
            facebook:
              clientId: 137685191866-re0l8qip4ekvkq0l5krnlkmvil7hqerj.apps.googleusercontent.com
              clientSecret: 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
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - public_profile
            github:
              clientId: 137685191866-re0l8qip4ekvkq0l5krnlkmvil7hqerj.apps.googleusercontent.com
              clientSecret: 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
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - user:email
                - read:user
          provider:
            facebook:
              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
cloud:
  aws:
    credentials:
      access-key: AKIA47LPLGSWEESBPNGR
      secret-key: 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
    s3:
      bucket: social-iamge
    region:
      static: ap-northeast-2
    stack:
      auto: false

app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect